/**
 * Standard Error Codes
 */

const ERROR_CODES = {
  // Authentication errors
  AUTH_INVALID_TOKEN: 'AUTH_001',
  AUTH_TOKEN_EXPIRED: 'AUTH_002',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_003',
  
  // Validation errors
  VALIDATION_FAILED: 'VAL_001',
  VALIDATION_EMAIL_INVALID: 'VAL_002',
  VALIDATION_REQUIRED_FIELD: 'VAL_003',
  
  // Business logic errors
  USER_NOT_FOUND: 'USR_001',
  USER_ALREADY_EXISTS: 'USR_002',
  LISTING_NOT_FOUND: 'LST_001',
  LISTING_UNAVAILABLE: 'LST_002',
  BOOKING_FAILED: 'BKG_001',
  PAYMENT_FAILED: 'PAY_001',
  
  // System errors
  DATABASE_ERROR: 'SYS_001',
  CACHE_ERROR: 'SYS_002',
  KAFKA_ERROR: 'SYS_003',
  EXTERNAL_SERVICE_ERROR: 'SYS_004'
};

module.exports = ERROR_CODES;

